services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: jauth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pg-data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728
    ports:
      - '5432:5432'
volumes:
  pg-data:
